### PR TITLE
Merge my changes back

### PR DESCRIPTION
**Pull request by TheTechRobo**
I am merging my changes as of January 1, 2020. I suggest squashing and merging these commits; there are 42.

# LIST OF CHANGES IN THIS FORK
- Change "Browse Applications" to "Start Shopping" so its more like the WSC
- Add .gitignore
- Fix some CSS
- Fix exit to wii menu button i think
- Elaborate a bit
- Create warning page
- Create a placeholder for patches
- Fix e.g. `./home` in certain pages to `/home`. This will make subpages function correctly.
- Create README.md

If you don't like any changes, simply tell me. :)

# SCREENSHOTS
image
image
image

### CODE REVIEW

**Comment by Artuto** [comment]
AHAHAHAHHAHAHAHA

**Comment by dhtdht020** [comment]
Thanks for your contribution. I don't understand what is the goal of this pull request. You are changing and adding many different things that were not requested nor needed, and you have made countless commits with minor changes, which makes it very hard to review.

**Comment by larsenv** [comment]
What is this?

**Comment by dhtdht020** [comment]
I am sorry, but I am going to close this pull request. If you want to know what's needed, you can ask in the Discord server or submit an idea in the [discussions](https://github.com/OpenShopChannel/WSC-Web/discussions) tab.
Additionally, please look into [cloning the repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/cloning-a-repository) to work with locally, rather than modifying every file separately through the website.

**Comment by TheTechRobo** [comment]
Sounds good. I'll take your advice in the future.

**Pull request closed without merging**
